openapi: '3.0.0'
info:
    version: 1.0.0
    title: Swagger Categorias
    description: Endpoint para la gestión de categorias
    termsOfService: http://swagger.io/terms/
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
    /api/categories:
        post:
            description: Registro de categorias
            operationId: createCategory
            requestBody:
                description: Los datos de la categoria a registrar
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Categories'
            responses:
                '200':
                    description: category response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Categories'
                default:
                    description: unexpected error
                    content: 
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            description: Lista las categorias registradas
            operationId: listCategories
            responses:
                '200':
                    description: category response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Categories'
                default:
                    description: unexpected error
                    content: 
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    
components:
    schemas:
        Categories:
            required:
                - id
                - name
            properties:
                id:
                    readOnly: true
                    type: string
                name:
                    type: string

        Error:
            required:
                - message
                - error
            properties:
                message:
                    type: string
                error:
                    type: boolean

    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            in: header
            name: X-API-Key
